name: Publish container images

on:
  workflow_dispatch:
  push:
    branches: 
      - 'UE*'
    paths: 
      - 'SignallingWebServer/package.json'

jobs:
  signalling-server-image:
    if: github.repository == 'EpicGames/PixelStreamingInfrastructure'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obtain the UE version from the branch name
        id: extract-version
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          echo "version=${BRANCH_NAME#UE}" >> $GITHUB_OUTPUT
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: pixelstreamingunofficial
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Signalling Server container image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: 'pixelstreamingunofficial/pixel-streaming-signalling-server:${{ steps.extract-version.outputs.version }}'
          push: true
          file: SignallingWebServer/Dockerfile

      - id: get-package-json
        run: |
          package_content=`cat SignallingWebServer/package.json`
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo $package_content >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create or update release tag
        uses: actions/github-script@v5
        with:
          script: |
            const tag = 'refs/tags/signalling-webserver-${{ github.ref_name }}-${{ fromJson(steps.get-package-json.outputs.json).version }}';
            try {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: tag,
                sha: context.sha
              });
            } catch (e) {
              if (e.status === 422) {
                await github.rest.git.updateRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: tag.replace('refs/', ''),
                  sha: context.sha,
                  force: true
                });
              } else {
                throw e;
              }
            }
